
CREATE TABLE CATEGORIES (
    ID int AUTO_INCREMENT PRIMARY KEY,
    NAME varchar(100),
    CODE varchar(100),
    DESCRIPTION varchar(100)
);

CREATE TABLE PRODUCTS (
    ID int AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100),
    PRICE DECIMAL(10,2),
    STOCK INT,
    CATEGORY_ID INT,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID)
);
